language: node_js
cache: npm
notifications:
  email: false
node_js:
  - "8"
  - "10"
install:
  - npm ci
script:
  - if [ $TRAVIS_PULL_REQUEST != false ]; then npm run lint; fi
  - if [ $TRAVIS_PULL_REQUEST != false ]; then npm run test:withCoverage; fi
before_deploy:
  - npm run build
deploy:
  on:
    node: 10
  provider: script
  skip_cleanup: true
  script:
    - npx semantic-release

after_success:
  - npx codecov
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
